version: '3.8'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@match.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
